Repository agentic-labs/lsproxy-python-sdk, pull requests merged in 2025-01, with the labels that each got.

#60 Add find_identifier method and related models to Lsproxy
  lsproxy/__init__.py
  lsproxy/client.py
  lsproxy/models.py
  pyproject.toml
Labels: size:M

#61 Cache the checkout
  lsproxy/client.py
  lsproxy/modal.py
Labels: size:L

#62 Add more logs
  lsproxy/modal.py
  pyproject.toml
Labels: size:XS
